/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.icculus.chunky.wordsmith.GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author chunky
 */
public class AddWordsPanel extends javax.swing.JPanel {

    MainWindow mw = null;
    
    /** Creates new form AddWordsPanel */
    public AddWordsPanel(MainWindow mw) {
        this.mw = mw;
        initComponents();
    }

    private BookListItem getSelectedBook() {
        return (BookListItem) bookCombo.getSelectedItem();
    }
    
    private ComboBoxModel<BookListItem> getBookComboModel() {
        DefaultComboBoxModel<BookListItem> m = new DefaultComboBoxModel<BookListItem>();
        try {
            List<BookListItem> bookListFromDB = BookListItem.getBookListFromDB(mw.getDbConn());
            for(BookListItem i : bookListFromDB) {
                m.addElement(i);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return m;
    }
    
    private void addWords() {
        Connection dbConn = mw.getDbConn();
        String sql = "INSERT INTO wordcount (bookid, delta) VALUES (?, ?)";
        BookListItem selectedBook = getSelectedBook();
        if(null == selectedBook) {
            JOptionPane.showMessageDialog(this, "No Book Selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try(PreparedStatement stmt = dbConn.prepareStatement(sql)) {
            stmt.setInt(1, selectedBook.getBookid());
            stmt.setInt(2, (Integer)deltaSpinner.getValue());
            stmt.executeUpdate();
            dbConn.commit();
            mw.updateCharts();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bookCombo = new javax.swing.JComboBox<>();
        deltaSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        bookCombo.setModel(getBookComboModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(bookCombo, gridBagConstraints);

        deltaSpinner.setModel(new javax.swing.SpinnerNumberModel(1000, null, null, 100));
        deltaSpinner.setMinimumSize(new java.awt.Dimension(80, 20));
        deltaSpinner.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(deltaSpinner, gridBagConstraints);

        jButton1.setText("<- Add Words");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addWords();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<BookListItem> bookCombo;
    private javax.swing.JSpinner deltaSpinner;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
